steps:


#build the wasm files for the static game and put them in the folder
- name: 'rust'
  args: ['./buildgamestatic.sh']
  id: 'firststep'
  waitFor: ['-']

#build the image for the static gamefinder that hosts them on 8000 with python webhost
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gamefinder_static:latest',  './gamefinder_static/']
  id: 'build_gamefinder_static'
  waitFor: ['firststep']  # wait for firststep

#build the image for the static gamefiles that hosts them on 8000 with python webhost
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gamefiles_static:latest',  './chesscheckersgame_static/']
  id: 'build_gamefiles_static'
  waitFor: ['firststep']  # wait for firststep



images:
- 'gcr.io/$PROJECT_ID/gamefinder_static:latest'
- 'gcr.io/$PROJECT_ID/gamefiles_static:latest'




# deploy the gamefile and gamefinder deployment

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'gamefile-deploy.yaml']
  waitFor: ['build_gamefiles_static']  # wait for firststep
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'gamefinder-deploy.yaml']
  waitFor: ['build_gamefinder_static']  # wait for firststep
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'



# deploy the gamefile and gamefinder service

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'gamefile-service.yaml']
  waitFor: ['build_gamefiles_static']  # wait for firststep
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'gamefinder-service.yaml']
  waitFor: ['build_gamefinder_static']  # wait for firststep
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'





