steps:

#build the image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/rocket-web:latest',  '.']
  id: 'build_static'
  waitFor: ['-']


#push the image to the repository
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/rocket-web:latest']
  id: 'push_image'
  waitFor: ['build_static']


#deploy it
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'deploy.yaml']
  waitFor: ['push_image']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'


#apply the service
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'service.yaml']
  waitFor: ['push_image']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'



timeout: 1800s
